"""fix review relationship

Revision ID: 1f8120f58903
Revises: f01020e9e016
Create Date: 2026-02-24 15:36:16.176708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8120f58903'
down_revision: Union[str, Sequence[str], None] = 'f01020e9e016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reservation_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'reviews', ['reservation_id'])
    op.drop_constraint(op.f('reviews_room_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'reservations', ['reservation_id'], ['reservation_id'])
    op.drop_column('reviews', 'room_id')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('reviews_room_id_fkey'), 'reviews', 'rooms', ['room_id'], ['room_id'])
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'reservation_id')
    # ### end Alembic commands ###
